### ISSUE TITLE
poetry is not supported by python version 3.13.1

### ISSUE THREAD

**Issue by winter-loo** [neondatabase/neon#10237]
Per the `docs/sourcetree.md`, 

>     - Our setup with poetry should work with newer python versions too. So feel free to open an issue with a `c/test-runner` label if something doesn't work as expected.

In my test on Arch Linux with python 3.13, `scripts/pysync` reports the following error:

```text
  error: failed to run custom build command for `pydantic-core v2.18.2 (/tmp/tmpbetu_x_0/pydantic_core-2.18.2)`

  Caused by:
    process didn't exit successfully: `/tmp/tmpbetu_x_0/pydantic_core-2.18.2/target/release/build/pydantic-core-349dee6109f9668e/build-script-build` (exit status: 101)
    --- stdout
    cargo:rustc-cfg=Py_3_6
    cargo:rustc-cfg=Py_3_7
    cargo:rustc-cfg=Py_3_8
    cargo:rustc-cfg=Py_3_9
    cargo:rustc-cfg=Py_3_10
    cargo:rustc-cfg=Py_3_11
    cargo:rustc-cfg=Py_3_12
    cargo:rustc-cfg=Py_3_13
    cargo:rustc-cfg=Py_LIMITED_API
    cargo:rerun-if-changed=python/pydantic_core/core_schema.py
    cargo:rerun-if-changed=generate_self_schema.py

    --- stderr
    Traceback (most recent call last):
      File "/tmp/tmpbetu_x_0/pydantic_core-2.18.2/generate_self_schema.py", line 193, in eval_forward_ref
        return type_._evaluate(core_schema.__dict__, None, set())
               ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    TypeError: ForwardRef._evaluate() missing 1 required keyword-only argument: 'recursive_guard'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/tmp/tmpbetu_x_0/pydantic_core-2.18.2/generate_self_schema.py", line 241, in <module>
        main()
        ~~~~^^
      File "/tmp/tmpbetu_x_0/pydantic_core-2.18.2/generate_self_schema.py", line 211, in main
        value = get_schema(s, definitions)
      File "/tmp/tmpbetu_x_0/pydantic_core-2.18.2/generate_self_schema.py", line 55, in get_schema
        return type_dict_schema(obj, definitions)
      File "/tmp/tmpbetu_x_0/pydantic_core-2.18.2/generate_self_schema.py", line 153, in type_dict_schema
        field_type = eval_forward_ref(field_type)
      File "/tmp/tmpbetu_x_0/pydantic_core-2.18.2/generate_self_schema.py", line 196, in eval_forward_ref
        return type_._evaluate(core_schema.__dict__, None)
               ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    TypeError: ForwardRef._evaluate() missing 1 required keyword-only argument: 'recursive_guard'
    thread 'main' panicked at build.rs:29:9:
    generate_self_schema.py failed with exit status: 1
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
  warning: build failed, waiting for other jobs to finish...
  💥 maturin failed
    Caused by: Failed to build a native library through cargo
    Caused by: Cargo build finished with "exit status: 101": `env -u CARGO PYO3_ENVIRONMENT_SIGNATURE="cpython-3.13-64bit" PYO3_PYTHON="/tmp/tmp439xc1i4/.venv/bin/python" PYTHON_SYS_EXECUTABLE="/tmp/tmp439xc1i4/.venv/bin/python" "cargo" "rustc" "--features" "pyo3/extension-module" "--message-format" "json-render-diagnostics" "--manifest-path" "/tmp/tmpbetu_x_0/pydantic_core-2.18.2/Cargo.toml" "--release" "--lib" "--crate-type" "cdylib"`
  Error: command ['maturin', 'pep517', 'build-wheel', '-i', '/tmp/tmp439xc1i4/.venv/bin/python', '--compatibility', 'off'] returned non-zero exit status 1


  at /usr/lib/python3.13/site-packages/poetry/installation/chef.py:164 in _prepare
      160│
      161│                 error = ChefBuildError("\n\n".join(message_parts))
      162│
      163│             if error is not None:
    → 164│                 raise error from None
      165│
      166│             return path
      167│
      168│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:

Note: This error originates from the build backend, and is likely not a problem with poetry but with pydantic-core (2.18.2) not supporting PEP 517 builds. You can verify this by running 'pip wheel --no-cache-dir --use-pep517 "pydantic-core (==2.18.2)"'.
```

I solved the problem by installing a new version python 3.11.9. Then everything goes well. [Here's a note of how I installed python 3.11.9](https://winter-loo.notion.site/test-166763aede9c8085b6c4dfee5d055207)

**Comment by jcsp** [comment]
Thanks for testing this.

pydantic is a transient dependency via `aws-sam-translator`, so we probably need to update that (pull in https://github.com/rkhwaja/rtmilk/pull/90)

**Comment by bayandin** [comment]
https://github.com/neondatabase/neon/pull/10285 should improve the quality of life with Python 3.13
