### ISSUE TITLE
Panic in Remote storage sync thread

### ISSUE THREAD

**Issue by hlinnaka** [neondatabase/neon#1719]
From pageserver logs in staging:
```
May 16 22:11:38 zenith-us-stage-ps-2.local pageserver[14336]: thread 'Remote storage sync thread' panicked at 'Hash table capacity overflow', /cargo/registry/src/github.com-1ecc6299db9ec823/hashbrown-0.11.0/src/raw/mod.rs:99:40
May 16 22:11:38 zenith-us-stage-ps-2.local pageserver[14336]: stack backtrace:
May 16 22:11:38 zenith-us-stage-ps-2.local pageserver[14336]:    0: rust_begin_unwind
May 16 22:11:38 zenith-us-stage-ps-2.local pageserver[14336]:              at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:498:5
May 16 22:11:38 zenith-us-stage-ps-2.local pageserver[14336]:    1: core::panicking::panic_fmt
May 16 22:11:38 zenith-us-stage-ps-2.local pageserver[14336]:              at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/panicking.rs:107:14
May 16 22:11:38 zenith-us-stage-ps-2.local pageserver[14336]:    2: core::panicking::panic
May 16 22:11:38 zenith-us-stage-ps-2.local pageserver[14336]:              at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/panicking.rs:48:5
May 16 22:11:38 zenith-us-stage-ps-2.local pageserver[14336]:    3: hashbrown::raw::Fallibility::capacity_overflow
May 16 22:11:38 zenith-us-stage-ps-2.local pageserver[14336]:              at /cargo/registry/src/github.com-1ecc6299db9ec823/hashbrown-0.11.0/src/raw/mod.rs:99:40
May 16 22:11:38 zenith-us-stage-ps-2.local pageserver[14336]:    4: hashbrown::raw::RawTableInner<A>::fallible_with_capacity
May 16 22:11:38 zenith-us-stage-ps-2.local pageserver[14336]:    5: hashbrown::raw::RawTable<T,A>::fallible_with_capacity
May 16 22:11:38 zenith-us-stage-ps-2.local pageserver[14336]:              at /cargo/registry/src/github.com-1ecc6299db9ec823/hashbrown-0.11.0/src/raw/mod.rs:468:20
May 16 22:11:38 zenith-us-stage-ps-2.local pageserver[14336]:    6: hashbrown::raw::RawTable<T,A>::with_capacity_in
May 16 22:11:38 zenith-us-stage-ps-2.local pageserver[14336]:              at /cargo/registry/src/github.com-1ecc6299db9ec823/hashbrown-0.11.0/src/raw/mod.rs:489:15
May 16 22:11:38 zenith-us-stage-ps-2.local pageserver[14336]:    7: hashbrown::raw::RawTable<T>::with_capacity
May 16 22:11:38 zenith-us-stage-ps-2.local pageserver[14336]:              at /cargo/registry/src/github.com-1ecc6299db9ec823/hashbrown-0.11.0/src/raw/mod.rs:419:9
May 16 22:11:38 zenith-us-stage-ps-2.local pageserver[14336]:    8: hashbrown::map::HashMap<K,V,S>::with_capacity_and_hasher
May 16 22:11:38 zenith-us-stage-ps-2.local pageserver[14336]:              at /cargo/registry/src/github.com-1ecc6299db9ec823/hashbrown-0.11.0/src/map.rs:392:20
May 16 22:11:38 zenith-us-stage-ps-2.local pageserver[14336]:    9: std::collections::hash::map::HashMap<K,V,S>::with_capacity_and_hasher
May 16 22:11:38 zenith-us-stage-ps-2.local pageserver[14336]:              at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/collections/hash/map.rs:308:25
May 16 22:11:38 zenith-us-stage-ps-2.local pageserver[14336]:   10: std::collections::hash::map::HashMap<K,V>::with_capacity
May 16 22:11:38 zenith-us-stage-ps-2.local pageserver[14336]:              at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/collections/hash/map.rs:247:9
May 16 22:11:38 zenith-us-stage-ps-2.local pageserver[14336]:   11: pageserver::storage_sync::SyncQueue::next_task_batch::{{closure}}
May 16 22:11:38 zenith-us-stage-ps-2.local pageserver[14336]:              at /home/circleci/project/pageserver/src/storage_sync.rs:513:27
May 16 22:11:38 zenith-us-stage-ps-2.local pageserver[14336]:   12: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
May 16 22:11:38 zenith-us-stage-ps-2.local pageserver[14336]:              at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/future/mod.rs:80:19
May 16 22:11:38 zenith-us-stage-ps-2.local pageserver[14336]:   13: pageserver::storage_sync::loop_step::{{closure}}
May 16 22:11:38 zenith-us-stage-ps-2.local pageserver[14336]:              at /home/circleci/project/pageserver/src/storage_sync.rs:961:25
May 16 22:11:38 zenith-us-stage-ps-2.local pageserver[14336]:   14: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
May 16 22:11:38 zenith-us-stage-ps-2.local pageserver[14336]:              at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/future/mod.rs:80:19
May 16 22:11:38 zenith-us-stage-ps-2.local pageserver[14336]:   15: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
May 16 22:11:38 zenith-us-stage-ps-2.local pageserver[14336]:              at /home/circleci/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.30/src/instrument.rs:272:9
May 16 22:11:38 zenith-us-stage-ps-2.local pageserver[14336]:   16: pageserver::storage_sync::storage_sync_loop::{{closure}}::{{closure}}
May 16 22:11:38 zenith-us-stage-ps-2.local pageserver[14336]:              at /home/circleci/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/macros/select.rs:505:49
May 16 22:11:38 zenith-us-stage-ps-2.local pageserver[14336]:   17: <tokio::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
May 16 22:11:38 zenith-us-stage-ps-2.local pageserver[14336]:              at /home/circleci/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/future/poll_fn.rs:38:9
May 16 22:11:38 zenith-us-stage-ps-2.local pageserver[14336]:   18: pageserver::storage_sync::storage_sync_loop::{{closure}}
May 16 22:11:38 zenith-us-stage-ps-2.local pageserver[14336]:              at /home/circleci/project/pageserver/src/storage_sync.rs:915:13
May 16 22:11:38 zenith-us-stage-ps-2.local pageserver[14336]:   19: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
May 16 22:11:38 zenith-us-stage-ps-2.local pageserver[14336]:              at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/future/mod.rs:80:19
May 16 22:11:38 zenith-us-stage-ps-2.local pageserver[14336]:   20: <core::pin::Pin<P> as core::future::future::Future>::poll
May 16 22:11:38 zenith-us-stage-ps-2.local pageserver[14336]:              at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/future/future.rs:119:9
May 16 22:11:38 zenith-us-stage-ps-2.local pageserver[14336]:   21: tokio::runtime::basic_scheduler::CoreGuard::block_on::{{closure}}::{{closure}}::{{closure}}
May 16 22:11:38 zenith-us-stage-ps-2.local pageserver[14336]:              at /home/circleci/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/basic_scheduler.rs:498:48
May 16 22:11:38 zenith-us-stage-ps-2.local pageserver[14336]:   22: tokio::coop::with_budget::{{closure}}
May 16 22:11:38 zenith-us-stage-ps-2.local pageserver[14336]:              at /home/circleci/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/coop.rs:102:9
May 16 22:11:38 zenith-us-stage-ps-2.local pageserver[14336]:   23: std::thread::local::LocalKey<T>::try_with
May 16 22:11:38 zenith-us-stage-ps-2.local pageserver[14336]:              at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/thread/local.rs:399:16
May 16 22:11:38 zenith-us-stage-ps-2.local pageserver[14336]:   24: std::thread::local::LocalKey<T>::with
May 16 22:11:38 zenith-us-stage-ps-2.local pageserver[14336]:              at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/thread/local.rs:375:9
May 16 22:11:38 zenith-us-stage-ps-2.local pageserver[14336]:   25: tokio::coop::with_budget
May 16 22:11:38 zenith-us-stage-ps-2.local pageserver[14336]:              at /home/circleci/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/coop.rs:95:5
May 16 22:11:38 zenith-us-stage-ps-2.local pageserver[14336]:   26: tokio::coop::budget
May 16 22:11:38 zenith-us-stage-ps-2.local pageserver[14336]:              at /home/circleci/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/coop.rs:72:5
May 16 22:11:38 zenith-us-stage-ps-2.local pageserver[14336]:   27: tokio::runtime::basic_scheduler::CoreGuard::block_on::{{closure}}::{{closure}}
May 16 22:11:38 zenith-us-stage-ps-2.local pageserver[14336]:              at /home/circleci/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/basic_scheduler.rs:498:25
May 16 22:11:38 zenith-us-stage-ps-2.local pageserver[14336]:   28: tokio::runtime::basic_scheduler::Context::enter
May 16 22:11:38 zenith-us-stage-ps-2.local pageserver[14336]:              at /home/circleci/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/basic_scheduler.rs:356:19
May 16 22:11:38 zenith-us-stage-ps-2.local pageserver[14336]:   29: tokio::runtime::basic_scheduler::CoreGuard::block_on::{{closure}}
May 16 22:11:38 zenith-us-stage-ps-2.local pageserver[14336]:              at /home/circleci/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/basic_scheduler.rs:497:36
May 16 22:11:38 zenith-us-stage-ps-2.local pageserver[14336]:   30: tokio::runtime::basic_scheduler::CoreGuard::enter::{{closure}}
May 16 22:11:38 zenith-us-stage-ps-2.local pageserver[14336]:              at /home/circleci/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/basic_scheduler.rs:555:57
May 16 22:11:38 zenith-us-stage-ps-2.local pageserver[14336]:   31: tokio::macros::scoped_tls::ScopedKey<T>::set
May 16 22:11:38 zenith-us-stage-ps-2.local pageserver[14336]:              at /home/circleci/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/macros/scoped_tls.rs:61:9
May 16 22:11:38 zenith-us-stage-ps-2.local pageserver[14336]:   32: tokio::runtime::basic_scheduler::CoreGuard::enter
May 16 22:11:38 zenith-us-stage-ps-2.local pageserver[14336]:              at /home/circleci/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/basic_scheduler.rs:555:27
May 16 22:11:38 zenith-us-stage-ps-2.local pageserver[14336]:   33: tokio::runtime::basic_scheduler::CoreGuard::block_on
May 16 22:11:38 zenith-us-stage-ps-2.local pageserver[14336]:              at /home/circleci/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/basic_scheduler.rs:488:9
May 16 22:11:38 zenith-us-stage-ps-2.local pageserver[14336]:   34: tokio::runtime::basic_scheduler::BasicScheduler::block_on
May 16 22:11:38 zenith-us-stage-ps-2.local pageserver[14336]:              at /home/circleci/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/basic_scheduler.rs:168:24
May 16 22:11:38 zenith-us-stage-ps-2.local pageserver[14336]:   35: tokio::runtime::Runtime::block_on
May 16 22:11:38 zenith-us-stage-ps-2.local pageserver[14336]:              at /home/circleci/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/mod.rs:475:46
May 16 22:11:38 zenith-us-stage-ps-2.local pageserver[14336]:   36: pageserver::storage_sync::storage_sync_loop
May 16 22:11:38 zenith-us-stage-ps-2.local pageserver[14336]:              at /home/circleci/project/pageserver/src/storage_sync.rs:914:25
May 16 22:11:38 zenith-us-stage-ps-2.local pageserver[14336]:   37: pageserver::storage_sync::spawn_storage_sync_thread::{{closure}}
May 16 22:11:38 zenith-us-stage-ps-2.local pageserver[14336]:              at /home/circleci/project/pageserver/src/storage_sync.rs:875:13
May 16 22:11:38 zenith-us-stage-ps-2.local pageserver[14336]:   38: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
May 16 22:11:38 zenith-us-stage-ps-2.local pageserver[14336]:              at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/panic/unwind_safe.rs:271:9
May 16 22:11:38 zenith-us-stage-ps-2.local pageserver[14336]:   39: std::panicking::try::do_call
May 16 22:11:38 zenith-us-stage-ps-2.local pageserver[14336]:              at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:406:40
May 16 22:11:38 zenith-us-stage-ps-2.local pageserver[14336]:   40: std::panicking::try
May 16 22:11:38 zenith-us-stage-ps-2.local pageserver[14336]:              at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:370:19
May 16 22:11:38 zenith-us-stage-ps-2.local pageserver[14336]:   41: std::panic::catch_unwind
May 16 22:11:38 zenith-us-stage-ps-2.local pageserver[14336]:              at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panic.rs:133:14
May 16 22:11:38 zenith-us-stage-ps-2.local pageserver[14336]:   42: pageserver::thread_mgr::thread_wrapper
May 16 22:11:38 zenith-us-stage-ps-2.local pageserver[14336]:              at /home/circleci/project/pageserver/src/thread_mgr.rs:223:18
May 16 22:11:38 zenith-us-stage-ps-2.local pageserver[14336]:   43: pageserver::thread_mgr::spawn::{{closure}}
May 16 22:11:38 zenith-us-stage-ps-2.local pageserver[14336]:              at /home/circleci/project/pageserver/src/thread_mgr.rs:175:13
May 16 22:11:38 zenith-us-stage-ps-2.local pageserver[14336]: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
May 16 22:11:38 zenith-us-stage-ps-2.local pageserver[14336]: 2022-05-16T22:11:38.285709Z ERROR Thread 'Remote storage sync thread' tenant_id: None, timeline_id: None panicked: Any { .. }
```

**Comment by hlinnaka** [comment]
The hash table size comes from an AtomicUsize variable that is incremented and decremented with atomic ops. `AtomicUsize::fetch_sub` wraps around on underflow; I bet that's what happened here even though I don't immediately see anything wrong with the increment/decrement logic.

**Comment by hlinnaka** [comment]
Hmm, could it be a simple race condition? In a nutshell, there's a queue and the counter for the number of items in the queue. The producer does this:

```
    fn push(&self, sync_id: ZTenantTimelineId, new_task: SyncTask) {
        match self.sender.send((sync_id, new_task)) {
            Ok(()) => {
                self.len.fetch_add(1, Ordering::Relaxed);
            }
            Err(e) => {
                error!("failed to push sync task to queue: {e}");
            }
        }
    }
```
and the consumer does this:
```
        let (first_sync_id, first_task) = if let Some(first_task) = sync_queue_receiver.recv().await
        {
            self.len.fetch_sub(1, Ordering::Relaxed);
            first_task
        } else {
            info!("Queue sender part was dropped, aborting");
            return HashMap::new();
        };
```
If the queue is previously empty, and the producer thread is paused after the call to `self.sender.send`, the consumer will receive the task from the queue and call `fetch_sub` before the consumer has called `fetch_add`, it will momentarily wrap around.

**Comment by hlinnaka** [comment]
As it happens, @bojanserafimov was working on a similar "task queue" for the compaction and GC threads just the other day. I suggested a scheme like this (in pseudo-code, won't compile as is):
```
// Have one global Deque of Jobs, protected by Mutex, and a condition variable
// for wakeups:

job_queue: Mutex<VecDeque<Job>>,
condvar: Condvar,

// At startup, launch N threads, each thread running this loop:

fn worker_main() {
    let mut q = job_queue.lock();
    loop {
        // Get next Job from queue
        if let Some(job) = q.pop_front() {
            // Got a job to run. Run it.
            drop(q);
            job.run();
            q = deque.lock();
        } else {
            // The job queue is empty. Wait for a new job to arrive
            condvar.wait(q);
        }
    }
}

fn queue_job(job: Job) {
    // Add the job to the back of the queue
    let mut q = job_queue.lock();
    q.push_back(job);

    // If the queue was empty, wake up the next worker thread to pick up
    // the job.
    if q.len() == 1 {
        condvar.notify_one();
    }
}
```
I think the same would work here.
