### ISSUE TITLE
`main` broken: `benchmarks` fail: could not translate host name `start.zenith.tech` to address

### ISSUE THREAD

**Issue by yeputons** [neondatabase/neon#1767]
It all started yesterday, e.g. https://app.circleci.com/pipelines/github/neondatabase/neon/6565/workflows/dcbdce47-8ac5-4e07-877e-fc3574e7a240/jobs/66412

```
===== 30 passed, 4 skipped, 3 deselected, 31 warnings in 962.64s (0:16:02) =====
+++ dirname -- scripts/generate_and_push_perf_report.sh
++ cd -- scripts
++ pwd
+ SCRIPT_DIR=/home/circleci/project/scripts
+ echo 'Uploading perf report to zenith pg'
Uploading perf report to zenith pg
+ DATABASE_URL='***********************************************************************************************************************************************************************************'
+ poetry run python /home/circleci/project/scripts/ingest_perf_test_result.py --ingest /home/circleci/project/test_runner/perf-report-local
Traceback (most recent call last):
  File "/home/circleci/project/scripts/ingest_perf_test_result.py", line 136, in <module>
    main()
  File "/home/circleci/project/scripts/ingest_perf_test_result.py", line 116, in main
    with get_connection_cursor() as cur:
  File "/home/circleci/.pyenv/versions/3.9.2/lib/python3.9/contextlib.py", line 117, in __enter__
    return next(self.gen)
  File "/home/circleci/project/scripts/ingest_perf_test_result.py", line 36, in get_connection_cursor
    with psycopg2.connect(connstr) as conn:
  File "/home/circleci/.cache/pypoetry/virtualenvs/zenith-3aSsmiER-py3.9/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "start.zenith.tech" to address: Name or service not known


Exited with code exit status 1

CircleCI received exit code 1
```

**Comment by cicdteam** [comment]
@LizardWizzard 
correct hostnames for prod defined [there](https://github.com/neondatabase/neon/blob/main/.circleci/helm-values/production.proxy.yaml#L25) for proxy and [there](https://github.com/neondatabase/neon/blob/main/.circleci/helm-values/production.proxy-scram.yaml#L17) for proxy with SCRAM

**Comment by LizardWizzard** [comment]
I changed the URL so it points to connect.neon.tech instead of start.zenith.tech. It still uses password-based flow because scram is not yet fully supported by our current production setup. I retried the latest attempt to upload results and it worked: https://app.circleci.com/pipelines/github/neondatabase/neon/6618/workflows/0e8732a3-0553-4f16-8b24-38521bbdd5a9/jobs/67112
