### ISSUE TITLE
`decryption failed or bad  record mac` error connecting with psycopg3

### ISSUE THREAD

**Issue by hlinnaka** [neondatabase/neon#1826]
From @volfco: 

> The driver connects but I get the following exception:

> OperationalError('consuming input failed: decryption failed or bad 
> record mac')
> Traceback (most recent call last):
>   File 
> "/home/colum/PycharmProjects/ao3_archiver/venv/lib/python3.10/site-packages/celery/app/trace.py", 
> line 451, in trace_task
>     R = retval = fun(*args, **kwargs)
>   File 
> "/home/colum/PycharmProjects/ao3_archiver/venv/lib/python3.10/site-packages/celery/app/trace.py", 
> line 734, in __protected_call__
>     return self.run(*args, **kwargs)
>   File "/home/colum/PycharmProjects/ao3_archiver/main.py", line 156, 
> in download_work
>     rs = cur.execute("SELECT ao3id FROM works WHERE ao3id = %s AND 
> ao3modified = %s",
>   File 
> "/home/colum/PycharmProjects/ao3_archiver/venv/lib/python3.10/site-packages/psycopg/cursor.py", 
> line 555, in execute
>     raise ex.with_traceback(None)
> psycopg.OperationalError: consuming input failed: decryption failed or 
> bad record mac

This seems to be specific to the python psycopg3 package. I'm unable to replicate it using Intellij DB Connection, which makes me think there's some incompatibility between the client and what you guys are doing.

**Comment by volfco** [comment]
Bit more context. This happens in a celery worker, as the traceroute indicates. 

```
[2022-05-28 10:41:56,554: ERROR/ForkPoolWorker-20] Task main.download_work[8f1d0540-6a5b-4feb-986c-85074dba5aa4] raised unexpected: OperationalError('consuming input failed: sslv3 alert bad record mac')
Traceback (most recent call last):
  File "/home/colum/PycharmProjects/ao3_archiver/venv/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/colum/PycharmProjects/ao3_archiver/venv/lib/python3.10/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/colum/PycharmProjects/ao3_archiver/main.py", line 156, in download_work
    cur.execute("SELECT ao3id FROM works WHERE ao3id = {} AND ao3modified = {}".format(ao3id, ao3modified))
  File "/home/colum/PycharmProjects/ao3_archiver/venv/lib/python3.10/site-packages/psycopg/cursor.py", line 555, in execute
    raise ex.with_traceback(None)
psycopg.OperationalError: consuming input failed: sslv3 alert bad record mac
[2022-05-28 10:41:56,555: ERROR/ForkPoolWorker-3] Task main.download_work[536cf923-ff6b-4706-b465-407866b9fc26] raised unexpected: OperationalError('consuming input failed: EOF detected')
Traceback (most recent call last):
  File "/home/colum/PycharmProjects/ao3_archiver/venv/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/colum/PycharmProjects/ao3_archiver/venv/lib/python3.10/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/colum/PycharmProjects/ao3_archiver/main.py", line 156, in download_work
    cur.execute("SELECT ao3id FROM works WHERE ao3id = {} AND ao3modified = {}".format(ao3id, ao3modified))
  File "/home/colum/PycharmProjects/ao3_archiver/venv/lib/python3.10/site-packages/psycopg/cursor.py", line 555, in execute
    raise ex.with_traceback(None)
psycopg.OperationalError: consuming input failed: EOF detected

```

Both these errors happen at the exact same time, but I'm unable to reproduce it when I'm not trying to send multiple queries concurrently.

**Comment by volfco** [comment]
This appears to be psycopg3 being weird, and nothing specific to Neon's implementation.

**Comment by hlinnaka** [comment]
I think this is the same issue as discussed here: https://stackoverflow.com/questions/53619971/ssl-error-bad-record-mac-managing-multiple-connections-with-postgresql-and-py. In a nutshell, you cannot share the same connection across different processes. I don't know how celery works, so I'm afraid I don't know what the proper way of doing that would be.

**Comment by volfco** [comment]
Yeah. It seems to be an issue with the driver and not you guys.

I sometimes forget about Python's weirdness after writing a lot of Rust.
