### ISSUE TITLE
CI failures because of cachepot: error: Connection to coordinator timed out

### ISSUE THREAD

**Issue by yeputons** [neondatabase/neon#2130]
Example: https://github.com/neondatabase/neon/runs/7413016828?check_suite_focus=true

```
Run ${cov_prefix} mold -run cargo build $CARGO_FLAGS --features failpoints --bins --tests
+ scripts/coverage --profraw-prefix=build-neon --dir=/tmp/coverage run mold -run cargo build --features failpoints --bins --tests
   Compiling workspace_hack v0.1.0 (/runner/_work/neon/neon/workspace_hack)
   Compiling postgres_ffi v0.1.0 (/runner/_work/neon/neon/libs/postgres_ffi)
cachepot: error: Connection to coordinator timed out
error: could not compile `postgres_ffi`
warning: build failed, waiting for other jobs to finish...
cachepot: error: Connection to coordinator timed out
error: build failed
Traceback (most recent call last):
  File "/runner/_work/neon/neon/scripts/coverage", line 594, in <module>
    main()
  File "/runner/_work/neon/neon/scripts/coverage", line 588, in main
    handler(args)
  File "/runner/_work/neon/neon/scripts/coverage", line 437, in do_run
    subprocess.check_call([*args.command, *args.args])
  File "/home/runner/.pyenv/versions/3.9.2/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['mold', '-run', 'cargo', 'build', '--features', 'failpoints', '--bins', '--tests']' returned non-zero exit status 101.
Error: Process completed with exit code 1.
```

**Comment by yeputons** [comment]
Still happens: https://github.com/neondatabase/neon/actions/runs/3715171443/jobs/6300009778

**Comment by SomeoneToIgnore** [comment]
Not appeared for a while and we have https://github.com/neondatabase/neon/issues/2586 for the removal already
