### ISSUE TITLE
Safekeeper panicked while holding TIMELINES_STATE mutex

### ISSUE THREAD

**Issue by petuhovskiy** [neondatabase/neon#2200]
After the panic TIMELINES_STATE mutex became poisoned and all subsequent timeline gets resulted in PoisonError. I wasn't able to find the panic itself, we probably should tweak our logger to print stacktrace for all panics.

The issue is probably connected to calling delete tenant endpoint, because we didn't see this issue before enabling that. There is a possible race condition in deleting a timeline, because it could be implicitly created concurrently with deletion, but it's not yet clear how it could cause panic and if it's indeed the issue.

The first PoisonError appeared on staging at `2022-07-31T13:19:35.490718Z`, the previous log before that was at `2022-07-31T13:19:13.663980Z`. I couldn't find logs in between, it's very strange, could they have been dropped?

**Comment by arssher** [comment]
> could they have been dropped?

Yes, see lines like `2022-08-03 07:09:59 | Suppressed 18238 messages from safekeeper.service`. That was due to ill cluster trying to fetch in busyloop WAL segment which wasn't found, I fixed that. Let's see if this repeats now.

I also increased RateLimit to reduce chance of losing logs again:
https://github.com/neondatabase/cloud/pull/1970

**Comment by arssher** [comment]
2022-08-04 02:25:02 | 2022-08-04T02:25:02.619537Z  INFO broker:{timeline=4a8dd72104349afe5e4e135c63ebf4d6}: timeline 53466ed253a1c866860c476e9bef1bbc restored thread 'broker thread' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', libs/postgres_ffi/src/xlog_utils.rs:399:41 stack backtrace:

This is the problem.

**Comment by petuhovskiy** [comment]
More context:
```
2022-08-04T02:25:02.619317Z  INFO deleting all timelines for tenant 4a8dd72104349afe5e4e135c63ebf4d6
2022-08-04T02:25:02.619408Z  INFO broker:{timeline=4a8dd72104349afe5e4e135c63ebf4d6}: loading control file ./4a8dd72104349afe5e4e135c63ebf4d6/53466ed253a1c866860c476e9bef1bbc/safekeeper.control
2022-08-04T02:25:02.619537Z  INFO broker:{timeline=4a8dd72104349afe5e4e135c63ebf4d6}: timeline 53466ed253a1c866860c476e9bef1bbc restored
       thread 'broker thread' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', libs/postgres_ffi/src/xlog_utils.rs:399:41
       stack backtrace:
       0: rust_begin_unwind
                 at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:498:5
       1: core::panicking::panic_fmt
                 at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/panicking.rs:107:14
       2: core::result::unwrap_failed
                 at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/result.rs:1613:5
       3: core::result::Result<T,E>::unwrap
                 at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/result.rs:1295:23
       4: postgres_ffi::xlog_utils::find_end_of_wal
                 at /home/runner/libs/postgres_ffi/src/xlog_utils.rs:399:18
       5: <safekeeper::wal_storage::PhysicalStorage as safekeeper::wal_storage::Storage>::init_storage
                 at /home/runner/safekeeper/src/wal_storage.rs:322:17
       6: safekeeper::safekeeper::SafeKeeper<CTRL,WAL>::new
                 at /home/runner/safekeeper/src/safekeeper.rs:523:9
       7: safekeeper::timeline::SharedState::restore
                 at /home/runner/safekeeper/src/timeline.rs:128:17
       8: safekeeper::timeline::GlobalTimelines::get
                 at /home/runner/safekeeper/src/timeline.rs:635:36
       9: safekeeper::broker::pull_loop::{{closure}}
                 at /home/runner/safekeeper/src/broker.rs:282:34
      10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
                 at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/future/mod.rs:80:19
      11: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
                 at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.0/src/runtime/task/core.rs:165:17
      12: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
                 at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.0/src/loom/std/unsafe_cell.rs:14:9
      13: tokio::runtime::task::core::CoreStage<T>::poll
                 at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.0/src/runtime/task/core.rs:155:13
      14: tokio::runtime::task::harness::poll_future::{{closure}}
                 at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.0/src/runtime/task/harness.rs:480:19
      15: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
                 at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/panic/unwind_safe.rs:271:9
      16: std::panicking::try::do_call
                 at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:406:40
      17: std::panicking::try
                 at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:370:19
      18: std::panic::catch_unwind
                 at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panic.rs:133:14
      19: tokio::runtime::task::harness::poll_future
                 at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.0/src/runtime/task/harness.rs:468:18
      20: tokio::runtime::task::harness::Harness<T,S>::poll_inner
                 at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.0/src/runtime/task/harness.rs:104:27
      21: tokio::runtime::task::harness::Harness<T,S>::poll
                 at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.0/src/runtime/task/harness.rs:57:15
      22: tokio::runtime::task::LocalNotified<S>::run
                 at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.0/src/runtime/task/mod.rs:381:9
      23: tokio::runtime::basic_scheduler::CoreGuard::block_on::{{closure}}::{{closure}}
                 at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.0/src/runtime/basic_scheduler.rs:582:25
      24: tokio::coop::with_budget::{{closure}}
                 at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.0/src/coop.rs:102:9
      25: std::thread::local::LocalKey<T>::try_with
                 at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/thread/local.rs:399:16
      26: std::thread::local::LocalKey<T>::with
                 at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/thread/local.rs:375:9
      27: tokio::coop::with_budget
                 at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.0/src/coop.rs:95:5
      28: tokio::coop::budget
                 at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.0/src/coop.rs:72:5
      29: tokio::runtime::basic_scheduler::Context::run_task::{{closure}}
                 at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.0/src/runtime/basic_scheduler.rs:302:29
      30: tokio::runtime::basic_scheduler::Context::enter
                 at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.0/src/runtime/basic_scheduler.rs:367:19
      31: tokio::runtime::basic_scheduler::Context::run_task
                 at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.0/src/runtime/basic_scheduler.rs:302:9
      32: tokio::runtime::basic_scheduler::CoreGuard::block_on::{{closure}}
                 at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.0/src/runtime/basic_scheduler.rs:581:34
      33: tokio::runtime::basic_scheduler::CoreGuard::enter::{{closure}}
                 at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.0/src/runtime/basic_scheduler.rs:613:57
      34: tokio::macros::scoped_tls::ScopedKey<T>::set
                 at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.0/src/macros/scoped_tls.rs:61:9
      35: tokio::runtime::basic_scheduler::CoreGuard::enter
                 at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.0/src/runtime/basic_scheduler.rs:613:27
      36: tokio::runtime::basic_scheduler::CoreGuard::block_on
                 at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.0/src/runtime/basic_scheduler.rs:533:19
      37: tokio::runtime::basic_scheduler::BasicScheduler::block_on
                 at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.0/src/runtime/basic_scheduler.rs:179:24
      38: tokio::runtime::Runtime::block_on
                 at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.0/src/runtime/mod.rs:482:46
      39: safekeeper::broker::thread_main
                 at /home/runner/safekeeper/src/broker.rs:40:5
      40: safekeeper::start_safekeeper::{{closure}}
                 at /home/runner/safekeeper/src/bin/safekeeper.rs:338:21
    note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
2022-08-04T02:25:02.622732Z  INFO DELETE /v1/tenant/4a8dd72104349afe5e4e135c63ebf4d6 200 OK
2022-08-04T02:25:02.727157Z  WARN broker: pull task panicked: JoinError::Panic(Id(10), ...)
thread 'broker thread' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', safekeeper/src/timeline.rs:630:48
    stack backtrace:
       0: rust_begin_unwind
                 at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:498:5
       1: core::panicking::panic_fmt
                 at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/panicking.rs:107:14
       2: core::result::unwrap_failed
                 at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/result.rs:1613:5
       3: core::result::Result<T,E>::unwrap
                 at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/result.rs:1295:23
       4: safekeeper::timeline::GlobalTimelines::get
                 at /home/runner/safekeeper/src/timeline.rs:630:25
       5: safekeeper::broker::pull_loop::{{closure}}
                 at /home/runner/safekeeper/src/broker.rs:282:34
       6: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
                 at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/future/mod.rs:80:19
       7: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
                 at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.0/src/runtime/task/core.rs:165:17
       8: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
                 at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.0/src/loom/std/unsafe_cell.rs:14:9
       9: tokio::runtime::task::core::CoreStage<T>::poll
                 at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.0/src/runtime/task/core.rs:155:13
      10: tokio::runtime::task::harness::poll_future::{{closure}}
                 at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.0/src/runtime/task/harness.rs:480:19
      11: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
                 at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/panic/unwind_safe.rs:271:9
      12: std::panicking::try::do_call
                 at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:406:40
      13: std::panicking::try
                 at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:370:19
      14: std::panic::catch_unwind
                 at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panic.rs:133:14
      15: tokio::runtime::task::harness::poll_future
                 at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.0/src/runtime/task/harness.rs:468:18
      16: tokio::runtime::task::harness::Harness<T,S>::poll_inner
                 at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.0/src/runtime/task/harness.rs:104:27
      17: tokio::runtime::task::harness::Harness<T,S>::poll
                 at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.0/src/runtime/task/harness.rs:57:15
      18: tokio::runtime::task::LocalNotified<S>::run
                 at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.0/src/runtime/task/mod.rs:381:9
      19: tokio::runtime::basic_scheduler::CoreGuard::block_on::{{closure}}::{{closure}}
                 at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.0/src/runtime/basic_scheduler.rs:582:25
      20: tokio::coop::with_budget::{{closure}}
                 at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.0/src/coop.rs:102:9
      21: std::thread::local::LocalKey<T>::try_with
                 at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/thread/local.rs:399:16
      22: std::thread::local::LocalKey<T>::with
                 at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/thread/local.rs:375:9
      23: tokio::coop::with_budget
                 at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.0/src/coop.rs:95:5
      24: tokio::coop::budget
                 at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.0/src/coop.rs:72:5
      25: tokio::runtime::basic_scheduler::Context::run_task::{{closure}}
                 at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.0/src/runtime/basic_scheduler.rs:302:29
      26: tokio::runtime::basic_scheduler::Context::enter
                 at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.0/src/runtime/basic_scheduler.rs:367:19
      27: tokio::runtime::basic_scheduler::Context::run_task
                 at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.0/src/runtime/basic_scheduler.rs:302:9
      28: tokio::runtime::basic_scheduler::CoreGuard::block_on::{{closure}}
                 at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.0/src/runtime/basic_scheduler.rs:581:34
      29: tokio::runtime::basic_scheduler::CoreGuard::enter::{{closure}}
                 at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.0/src/runtime/basic_scheduler.rs:613:57
      30: tokio::macros::scoped_tls::ScopedKey<T>::set
                 at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.0/src/macros/scoped_tls.rs:61:9
      31: tokio::runtime::basic_scheduler::CoreGuard::enter
                 at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.0/src/runtime/basic_scheduler.rs:613:27
      32: tokio::runtime::basic_scheduler::CoreGuard::block_on
                 at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.0/src/runtime/basic_scheduler.rs:533:19
      33: tokio::runtime::basic_scheduler::BasicScheduler::block_on
                 at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.0/src/runtime/basic_scheduler.rs:179:24
      34: tokio::runtime::Runtime::block_on
                 at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.0/src/runtime/mod.rs:482:46
      35: safekeeper::broker::thread_main
                 at /home/runner/safekeeper/src/broker.rs:40:5
      36: safekeeper::start_safekeeper::{{closure}}
                 at /home/runner/safekeeper/src/bin/safekeeper.rs:338:21
    note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```
