### ISSUE TITLE
Drizzle migrations receive connection errors

### ISSUE THREAD

**Issue by spigelli** [neondatabase/neon#5098]
## Expected result
Migration script is able to connect successfully

## Actual result
The script is not able to connect to the database

## Environment
Node 18

## Logs, links
Drizzle migration script:

```ts
import { drizzle } from 'drizzle-orm/neon-http';
import { migrate } from 'drizzle-orm/neon-http/migrator';
import { raise } from '../util/raise.ts';
import { neon } from '@neondatabase/serverless';
import * as dotenv from 'dotenv';

dotenv.config({
  path: './.env.local',
});

console.info('Using environment variables:');
console.info(JSON.stringify(process.env, null, 2));

const url = process.env.DATABASE_URL ?? raise('DATABASE_URL is not set');

const sql = neon(url);
const db = drizzle(sql);

migrate(db, { migrationsFolder: 'src/data/migrations' });
```

Running this locally, it hangs indefinitely. In preview deployments on nextjs, it times out. Tried running migrations with the plain `pg` driver as well which did not work

**Comment by spigelli** [comment]
Also from the drizzle discord:
<img width="979" alt="image" src="https://github.com/neondatabase/neon/assets/25208877/87502edf-93de-4495-8c0d-2a56598c3cbf">

**Comment by spigelli** [comment]
I receive
```
NeonDbError: Error connecting to database: fetch failed
    at /Users/isaacspiegel/Documents/drop-of-wisdom/drop-of-wisdom/node_modules/@neondatabase/serverless/index.js:1523:86
    at async migrate (/Users/isaacspiegel/Documents/drop-of-wisdom/drop-of-wisdom/node_modules/src/neon-http/migrator.ts:26:2) {
  code: null,
  sourceError: TypeError: fetch failed
      at Object.fetch (node:internal/deps/undici/undici:11457:11)
      at async /Users/isaacspiegel/Documents/drop-of-wisdom/drop-of-wisdom/node_modules/@neondatabase/serverless/index.js:1521:61
      at async migrate (/Users/isaacspiegel/Documents/drop-of-wisdom/drop-of-wisdom/node_modules/src/neon-http/migrator.ts:26:2) {
    cause: HeadersTimeoutError: Headers Timeout Error
        at Timeout.onParserTimeout [as callback] (node:internal/deps/undici/undici:9647:32)
        at Timeout.onTimeout [as _onTimeout] (node:internal/deps/undici/undici:7948:17)
        at listOnTimeout (node:internal/timers:569:17)
        at processTimers (node:internal/timers:512:7) {
      code: 'UND_ERR_HEADERS_TIMEOUT'
    }
  }
}
error Command failed with exit code 1.
```
Team is blocked on this, so any help is much appreciated 🙏

**Comment by vadim2404** [comment]
hey @spigelli.

Thanks for submitting the issue. We found the bug on our side. WIll try to ship the fix to prod ASAP

**Comment by vadim2404** [comment]
@spigelli, we shipped the patch to prod. May I ask you to recheck?

**Comment by spigelli** [comment]
Yes it is working now, surprised at the turn around on this! Thanks!
