### ISSUE TITLE
"Error connecting to database: fetch failed" using drizzle and SST

### ISSUE THREAD

**Issue by nvsd** [neondatabase/neon#5362]
## Steps to reproduce
use neon with drizzle and attempt to connect to neon from an SST function
```typescript
import { neon, neonConfig } from "@neondatabase/serverless";
import { drizzle } from "drizzle-orm/neon-http";

neonConfig.fetchConnectionCache = true;

const sql = neon(process.env.DATABASE_URL!);
export const db = drizzle(sql);

// in SST function
export const get = ApiHandler(async (_evt) => {
  const data = await db.select().from(someTable).execute();
  const body = JSON.stringify(data);

  return ok(body);
});

```

## Expected result
Able to query data from neon database over http

## Actual result
serverless function times out

## Environment
serverless?

## Logs, links
```
Error: Error connecting to database: fetch failed
       at execute (/Users/zack/Projects/api/node_modules/.pnpm/@neondatabase+serverless@0.6.0/node_modules/@neondatabase/serverless/index.js:1533:49)
       at NeonHttpPreparedQuery.execute (/Users/zack/Projects/api/node_modules/.pnpm/drizzle-orm@0.28.6_@aws-sdk+client-rds-data@3.413.0_@neondatabase+serverless@0.6.0_kysely@0.2_37yoyvqj3lzqjkmyukc4pac6mi/node_modules/src/neon-http/session.ts:57:18)
       at <anonymous> (/Users/zack/Projects/api/packages/functions/src/exercises.ts:8:33)
       at <anonymous> (/Users/zack/Projects/api/node_modules/.pnpm/sst@2.25.1/node_modules/sst/node/api/index.js:28:22)
       at async file:///Users/zack/Projects/api/node_modules/.pnpm/sst@2.25.1/node_modules/sst/support/nodejs-runtime/index.mjs:148:16
 ```

**Comment by nvsd** [comment]
I might be using the wrong URL for serverless HTTP. The one I'm using is `postgres://<username>:<password@<URI>/<db>`

**Comment by kam-st** [comment]
Were you able to resolve this? The direct connection via npx drizzle-kit push works. But have same issue.

It is not the issue with url, as this postgres url works with other drivers.

**Comment by yita0101** [comment]
neon.tech  use this server.you will get a connect link like

**Comment by yita0101** [comment]
![image](https://github.com/neondatabase/neon/assets/67113472/e0ae1279-cee9-40a1-aad1-020a879a0c42)

**Comment by GokulDas027** [comment]
This is probably caused by your network/dns.
I had this `Error during migration: NeonDbError: Error connecting to database: fetch failed` during migrations, and was fixed using cloudflare warp.

**Comment by cliffordkleinsr** [comment]
See [here](https://github.com/nodejs/undici/issues/2990#issuecomment-2408883876)

**Comment by effessdev** [comment]
In my case, it got resolved when I added the following line to `~/.bashrc` as per the comment mentioned by @cliffordkleinsr:

```bash
export NODE_OPTIONS="network-family-autoselection-attempt-timeout=500"
```

More information: <https://github.com/nodejs/undici/issues/2990#issuecomment-2408882992>
