### ISSUE TITLE
safekeeper panics in find_end_of_wal_segment

### ISSUE THREAD

**Issue by petuhovskiy** [neondatabase/neon#932]
Happened in test_restarts_under_load running in [CI job 28426](https://app.circleci.com/pipelines/github/zenithdb/zenith/3386/workflows/087b05fe-8d7a-42c9-8e4c-e3d289afcdec/jobs/28426/tests#failed-test-0). One of the safekeepers panicked with `'attempt to subtract with overflow'`, postgres_ffi/src/xlog_utils.rs:198:23.

<details>
<summary>Full stacktrace from sk2/safekeeper.log</summary>

```
2021-11-19T14:38:34.624712Z  INFO creating timeline dir 19e0a56a95188c69230e13f68ea0a509, create is True
2021-11-19T14:38:34.624835Z  INFO loading control file ./19e0a56a95188c69230e13f68ea0a509/safekeeper.control, create=True lock file "./19e0a56a95188c69230e13f68ea0a509/safekeeper.lock"
thread 'WAL service thread' panicked at 'attempt to subtract with overflow', postgres_ffi/src/xlog_utils.rs:198:23
stack backtrace:
   0: rust_begin_unwind
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:515:5
   1: core::panicking::panic_fmt
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/panicking.rs:92:14
   2: core::panicking::panic
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/panicking.rs:50:5
   3: postgres_ffi::xlog_utils::find_end_of_wal_segment
             at /home/circleci/project/postgres_ffi/src/xlog_utils.rs:198:23
   4: postgres_ffi::xlog_utils::find_end_of_wal
             at /home/circleci/project/postgres_ffi/src/xlog_utils.rs:306:25
   5: walkeeper::timeline::SharedState::create_restore
             at /home/circleci/project/walkeeper/src/timeline.rs:141:13
   6: walkeeper::timeline::GlobalTimelines::get
             at /home/circleci/project/walkeeper/src/timeline.rs:426:36
   7: <core::option::Option<alloc::sync::Arc<walkeeper::timeline::Timeline>> as walkeeper::timeline::TimelineTools>::set
             at /home/circleci/project/walkeeper/src/timeline.rs:389:22
   8: <walkeeper::send_wal::SendWalHandler as zenith_utils::postgres_backend::Handler>::process_query
             at /home/circleci/project/walkeeper/src/send_wal.rs:58:17
   9: zenith_utils::postgres_backend::PostgresBackend::process_message
             at /home/circleci/project/zenith_utils/src/postgres_backend.rs:422:33
  10: zenith_utils::postgres_backend::PostgresBackend::run_message_loop
             at /home/circleci/project/zenith_utils/src/postgres_backend.rs:274:31
  11: zenith_utils::postgres_backend::PostgresBackend::run
             at /home/circleci/project/zenith_utils/src/postgres_backend.rs:256:19
  12: walkeeper::wal_service::handle_socket
             at /home/circleci/project/walkeeper/src/wal_service.rs:44:5
  13: walkeeper::wal_service::thread_main::{{closure}}
             at /home/circleci/project/walkeeper/src/wal_service.rs:25:43
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'http_endpoint_thread' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', walkeeper/src/timeline.rs:415:46
stack backtrace:
   0: rust_begin_unwind
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:515:5
   1: core::panicking::panic_fmt
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/panicking.rs:92:14
   2: core::result::unwrap_failed
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/result.rs:1599:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/result.rs:1281:23
   4: walkeeper::timeline::GlobalTimelines::get
             at /home/circleci/project/walkeeper/src/timeline.rs:415:29
   5: walkeeper::http::routes::timeline_status_handler::{{closure}}
             at /home/circleci/project/walkeeper/src/http/routes.rs:71:15
   6: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/future/mod.rs:80:19
   7: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/future/future.rs:119:9
   8: routerify::route::Route<B,E>::process::{{closure}}
             at /home/circleci/.cargo/registry/src/github.com-1ecc6299db9ec823/routerify-2.2.0/src/route/mod.rs:105:9
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/future/mod.rs:80:19
  10: routerify::router::Router<B,E>::process::{{closure}}
             at /home/circleci/.cargo/registry/src/github.com-1ecc6299db9ec823/routerify-2.2.0/src/router/mod.rs:308:46
  11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/future/mod.rs:80:19
  12: <routerify::service::request_service::RequestService<B,E> as tower_service::Service<http::request::Request<hyper::body::body::Body>>>::call::{{closure}}
             at /home/circleci/.cargo/registry/src/github.com-1ecc6299db9ec823/routerify-2.2.0/src/service/request_service.rs:56:13
  13: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/future/mod.rs:80:19
  14: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/future/future.rs:119:9
  15: <hyper::proto::h1::dispatch::Server<S,hyper::body::body::Body> as hyper::proto::h1::dispatch::Dispatch>::poll_msg
             at /home/circleci/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.14.13/src/proto/h1/dispatch.rs:491:35
  16: hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_write
             at /home/circleci/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.14.13/src/proto/h1/dispatch.rs:297:43
  17: hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_loop
             at /home/circleci/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.14.13/src/proto/h1/dispatch.rs:161:21
  18: hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_inner
             at /home/circleci/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.14.13/src/proto/h1/dispatch.rs:137:16
  19: hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_catch
             at /home/circleci/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.14.13/src/proto/h1/dispatch.rs:120:28
  20: <hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T> as core::future::future::Future>::poll
             at /home/circleci/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.14.13/src/proto/h1/dispatch.rs:424:9
  21: <hyper::server::conn::ProtoServer<T,B,S,E> as core::future::future::Future>::poll
             at /home/circleci/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.14.13/src/server/conn.rs:1061:47
  22: <hyper::server::conn::upgrades::UpgradeableConnection<I,S,E> as core::future::future::Future>::poll
             at /home/circleci/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.14.13/src/server/conn.rs:1265:30
  23: <hyper::common::drain::Watching<F,FN> as core::future::future::Future>::poll
             at /home/circleci/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.14.13/src/common/drain.rs:95:36
  24: <hyper::server::conn::spawn_all::NewSvcTask<I,N,S,E,W> as core::future::future::Future>::poll
             at /home/circleci/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.14.13/src/server/conn.rs:1202:36
  25: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
             at /home/circleci/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/task/core.rs:161:17
  26: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/circleci/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/loom/std/unsafe_cell.rs:14:9
  27: tokio::runtime::task::core::CoreStage<T>::poll
             at /home/circleci/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/task/core.rs:151:13
  28: tokio::runtime::task::harness::poll_future::{{closure}}
             at /home/circleci/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/task/harness.rs:461:19
  29: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panic.rs:347:9
  30: std::panicking::try::do_call
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:401:40
  31: __rust_try
  32: std::panicking::try
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:365:19
  33: std::panic::catch_unwind
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panic.rs:434:14
  34: tokio::runtime::task::harness::poll_future
             at /home/circleci/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/task/harness.rs:449:18
  35: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /home/circleci/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/task/harness.rs:98:27
  36: tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/circleci/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/task/harness.rs:53:15
  37: tokio::runtime::task::raw::poll
             at /home/circleci/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/task/raw.rs:113:5
  38: tokio::runtime::task::raw::RawTask::poll
             at /home/circleci/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/task/raw.rs:70:18
  39: tokio::runtime::task::LocalNotified<S>::run
             at /home/circleci/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/task/mod.rs:343:9
  40: tokio::runtime::basic_scheduler::Inner<P>::block_on::{{closure}}::{{closure}}
             at /home/circleci/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/basic_scheduler.rs:287:52
  41: tokio::coop::with_budget::{{closure}}
             at /home/circleci/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/coop.rs:106:9
  42: std::thread::local::LocalKey<T>::try_with
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/thread/local.rs:399:16
  43: std::thread::local::LocalKey<T>::with
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/thread/local.rs:375:9
  44: tokio::coop::with_budget
             at /home/circleci/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/coop.rs:99:5
  45: tokio::coop::budget
             at /home/circleci/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/coop.rs:76:5
  46: tokio::runtime::basic_scheduler::Inner<P>::block_on::{{closure}}
             at /home/circleci/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/basic_scheduler.rs:287:29
  47: tokio::runtime::basic_scheduler::enter::{{closure}}
             at /home/circleci/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/basic_scheduler.rs:339:29
  48: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /home/circleci/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/macros/scoped_tls.rs:61:9
  49: tokio::runtime::basic_scheduler::enter
             at /home/circleci/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/basic_scheduler.rs:339:5
  50: tokio::runtime::basic_scheduler::Inner<P>::block_on
             at /home/circleci/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/basic_scheduler.rs:218:9
  51: tokio::runtime::basic_scheduler::InnerGuard<P>::block_on
             at /home/circleci/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/basic_scheduler.rs:489:9
  52: tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on
             at /home/circleci/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/basic_scheduler.rs:178:24
  53: tokio::runtime::Runtime::block_on
             at /home/circleci/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/mod.rs:461:46
  54: zenith_utils::http::endpoint::serve_thread_main
             at /home/circleci/project/zenith_utils/src/http/endpoint.rs:188:5
  55: safekeeper::start_safekeeper::{{closure}}
             at /home/circleci/project/walkeeper/src/bin/safekeeper.rs:162:13
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```

</details>

https://github.com/zenithdb/zenith/blob/70ab0d5b1f0137f6aab89881fcd73e2c959bbfd9/postgres_ffi/src/xlog_utils.rs#L187-L198

I guess we just need to handle `xt_tot_len < 4` case?

**Comment by LizardWizzard** [comment]
Happened in https://app.circleci.com/pipelines/github/zenithdb/zenith/3414/workflows/3d06a63a-e16f-4a5e-abc9-2e277d209a82/jobs/28737/artifacts too

**Comment by stepashka** [comment]
does anyone know if this is still relevant?

**Comment by petuhovskiy** [comment]
It still can panic if data is corrupted and `0 < xt_tot_len < 4`, but I haven't seen it in tests for a while.

**Comment by arssher** [comment]
Finding end of WAL has been rewritten to handle cross segment boundary properly; I believe this is fixed.
