### ISSUE TITLE
Index prefetch attemtps to prefetch invalid blocks

### ISSUE THREAD

**Issue by alexanderlaw** [neondatabase/neon#9866]
Initially, I discovered this issue when running several test_pg_regress instances in a loop. Then I reproduced it with a reduced schedule, like this:
```
parallel group (6 tests):  hash_part partition_info partition_aggregate partition_prune partition_join indexing
     partition_join               ... ok         4112 ms
     partition_prune              ... ok         4036 ms
     hash_part                    ... ok          267 ms
     indexing                     ... ok         4462 ms
     partition_aggregate          ... ok         3980 ms
     partition_info               ... ok          684 ms
test oidjoins                     ... FAILED (test process exited with exit code 2)     2568 ms
```
(Later I found out that only indexing (repeated) is enough to trigger the issue.)

```
PG:TRAP: FailedAssertion("BlockNumberIsValid(blockNum)", File: ".../neon//vendor/postgres-v14/src/backend/storage/buffer/bufmgr.c", Line: 594, PID: 1075005)
postgres: cloud_admin regression 127.0.0.1(50626) DO(ExceptionalCondition+0xd6)[0x5569a9d6e86e]
postgres: cloud_admin regression 127.0.0.1(50626) DO(PrefetchBuffer+0x73)[0x5569a9b55509]
postgres: cloud_admin regression 127.0.0.1(50626) DO(_bt_first+0xf5c)[0x5569a96f254a]
postgres: cloud_admin regression 127.0.0.1(50626) DO(btgettuple+0x19b)[0x5569a96ec878]
postgres: cloud_admin regression 127.0.0.1(50626) DO(index_getnext_tid+0x18b)[0x5569a96d6958]
postgres: cloud_admin regression 127.0.0.1(50626) DO(+0x7a1854)[0x5569a9cfa854]
postgres: cloud_admin regression 127.0.0.1(50626) DO(+0x7a136f)[0x5569a9cfa36f]
...
PG:2024-11-21 06:49:52.430 GMT [1063326] DETAIL:  Failed process was running: DO $doblock$
    declare
     fk record;
    nkeys integer;
...
Core was generated by `postgres: cloud_admin regression 127.0.0.1(50626) DO                          '.
Program terminated with signal SIGABRT, Aborted.
...
#5  0x00005569a9d6e8a1 in ExceptionalCondition (conditionName=0x5569a9f436fa "BlockNumberIsValid(blockNum)", errorType=0x5569a9f435d9 "FailedAssertion", fileName=0x5569a9f43598 ".../neon//vendor/postgres-v14/src/backend/storage/buffer/bufmgr.c", lineNumber=594) at .../neon//vendor/postgres-v14/src/backend/utils/error/assert.c:69
#6  0x00005569a9b55509 in PrefetchBuffer (reln=0x7f2ce1636b88, forkNum=MAIN_FORKNUM, blockNum=4294967295) at .../neon//vendor/postgres-v14/src/backend/storage/buffer/bufmgr.c:594
#7  0x00005569a96f254a in _bt_first (scan=0x5569abb51518, dir=BackwardScanDirection) at .../neon//vendor/postgres-v14/src/backend/access/nbtree/nbtsearch.c:1484
#8  0x00005569a96ec878 in btgettuple (scan=0x5569abb51518, dir=BackwardScanDirection) at .../neon//vendor/postgres-v14/src/backend/access/nbtree/nbtree.c:242
#9  0x00005569a96d6958 in index_getnext_tid (scan=0x5569abb51518, direction=BackwardScanDirection) at .../neon//vendor/postgres-v14/src/backend/access/index/indexam.c:575
#10 0x00005569a9cfa854 in get_actual_variable_endpoint (heapRel=0x7f2cddc74e90, indexRel=0x7f2ce1636b88, indexscandir=BackwardScanDirection, scankeys=0x7ffc407fde80, typLen=4, typByVal=true, tableslot=0x5569abb51300, outercontext=0x5569aba97ad0, endpointDatum=0x5569abbcd5b0) at .../neon//vendor/postgres-v14/src/backend/utils/adt/selfuncs.c:6229
#11 0x00005569a9cfa36f in get_actual_variable_range (root=0x5569abbb90e8, vardata=0x7ffc407fe220, sortop=609, collation=0, min=0x0, max=0x5569abbcd5b0) at .../neon//vendor/postgres-v14/src/backend/utils/adt/selfuncs.c:6108
#12 0x00005569a9cf09b7 in ineq_histogram_selectivity (root=0x5569abbb90e8, vardata=0x7ffc407fe220, opoid=611, opproc=0x7ffc407fe100, isgt=false, iseq=true, collation=0, constval=26439, consttype=26) at .../neon//vendor/postgres-v14/src/backend/utils/adt/selfuncs.c:1126
#13 0x00005569a9cefd28 in scalarineqsel (root=0x5569abbb90e8, operator=611, isgt=false, iseq=true, collation=0, vardata=0x7ffc407fe220, constval=26439, consttype=26) at .../neon//vendor/postgres-v14/src/backend/utils/adt/selfuncs.c:685
#14 0x00005569a9cf4ab9 in mergejoinscansel (root=0x5569abbb90e8, clause=0x5569abbbba88, opfamily=1989, strategy=1, nulls_first=false, leftstart=0x7ffc407fe2e0, leftend=0x7ffc407fe2e8, rightstart=0x7ffc407fe2f0, rightend=0x7ffc407fe310) at .../neon//vendor/postgres-v14/src/backend/utils/adt/selfuncs.c:3099
#15 0x00005569a9a2252f in cached_scansel (root=0x5569abbb90e8, rinfo=0x5569abbbd5e0, pathkey=0x5569abbcda68) at .../neon//vendor/postgres-v14/src/backend/optimizer/path/costsize.c:3687
#16 0x00005569a9a2168d in initial_cost_mergejoin (root=0x5569abbb90e8, workspace=0x7ffc407fe510, jointype=JOIN_ANTI, mergeclauses=0x5569abbcdad8, outer_path=0x5569abbcabb8, inner_path=0x5569abbcad00, outersortkeys=0x5569abbcd970, innersortkeys=0x5569abbcdb88, extra=0x7ffc407fe6e0) at .../neon//vendor/postgres-v14/src/backend/optimizer/path/costsize.c:3249
#17 0x00005569a9a34e0c in try_mergejoin_path (root=0x5569abbb90e8, joinrel=0x5569abbcb888, outer_path=0x5569abbcabb8, inner_path=0x5569abbcad00, pathkeys=0x0, mergeclauses=0x5569abbcdad8, outersortkeys=0x5569abbcd970, innersortkeys=0x5569abbcdb88, jointype=JOIN_ANTI, extra=0x7ffc407fe6e0, is_partial=false) at .../neon//vendor/postgres-v14/src/backend/optimizer/path/joinpath.c:910
#18 0x00005569a9a359a4 in sort_inner_and_outer (root=0x5569abbb90e8, joinrel=0x5569abbcb888, outerrel=0x5569abb94bd8, innerrel=0x5569abbbbf28, jointype=JOIN_ANTI, extra=0x7ffc407fe6e0) at .../neon//vendor/postgres-v14/src/backend/optimizer/path/joinpath.c:1333
#19 0x00005569a9a33dc6 in add_paths_to_joinrel (root=0x5569abbb90e8, joinrel=0x5569abbcb888, outerrel=0x5569abb94bd8, innerrel=0x5569abbbbf28, jointype=JOIN_ANTI, sjinfo=0x5569abbbd498, restrictlist=0x5569abbccf78) at .../neon//vendor/postgres-v14/src/backend/optimizer/path/joinpath.c:282
#20 0x00005569a9a38e5f in populate_joinrel_with_paths (root=0x5569abbb90e8, rel1=0x5569abb94bd8, rel2=0x5569abbbbf28, joinrel=0x5569abbcb888, sjinfo=0x5569abbbd498, restrictlist=0x5569abbccf78) at .../neon//vendor/postgres-v14/src/backend/optimizer/path/joinrels.c:915
#21 0x00005569a9a388cc in make_join_rel (root=0x5569abbb90e8, rel1=0x5569abb94bd8, rel2=0x5569abbbbf28) at .../neon//vendor/postgres-v14/src/backend/optimizer/path/joinrels.c:760
#22 0x00005569a9a37dfc in make_rels_by_clause_joins (root=0x5569abbb90e8, old_rel=0x5569abb94bd8, other_rels_list=0x5569abbcce20, other_rels=0x5569abbcce40) at .../neon//vendor/postgres-v14/src/backend/optimizer/path/joinrels.c:312
#23 0x00005569a9a37917 in join_search_one_level (root=0x5569abbb90e8, level=2) at .../neon//vendor/postgres-v14/src/backend/optimizer/path/joinrels.c:123
#24 0x00005569a9a185c1 in standard_join_search (root=0x5569abbb90e8, levels_needed=2, initial_rels=0x5569abbcce20) at .../neon//vendor/postgres-v14/src/backend/optimizer/path/allpaths.c:3021
#25 0x00005569a9a18527 in make_rel_from_joinlist (root=0x5569abbb90e8, joinlist=0x5569abbbe580) at .../neon//vendor/postgres-v14/src/backend/optimizer/path/allpaths.c:2952
#26 0x00005569a9a13d53 in make_one_rel (root=0x5569abbb90e8, joinlist=0x5569abbbe580) at .../neon//vendor/postgres-v14/src/backend/optimizer/path/allpaths.c:228
#27 0x00005569a9a5408d in query_planner (root=0x5569abbb90e8, qp_callback=0x5569a9a59dfb <standard_qp_callback>, qp_extra=0x7ffc407febc0) at .../neon//vendor/postgres-v14/src/backend/optimizer/plan/planmain.c:276
#28 0x00005569a9a568b7 in grouping_planner (root=0x5569abbb90e8, tuple_fraction=0) at .../neon//vendor/postgres-v14/src/backend/optimizer/plan/planner.c:1442
#29 0x00005569a9a55f50 in subquery_planner (glob=0x5569abbc4130, parse=0x5569abb934f0, parent_root=0x0, hasRecursion=false, tuple_fraction=0) at .../neon//vendor/postgres-v14/src/backend/optimizer/plan/planner.c:1019
...
```

Notice the blockNum value passed to PrefetchBuffer().

With some logging added inside the "Start prefetching" code block, I got the following diagnostics:
```
PG:2024-11-21 18:09:54.280 GMT [3461271] LOG:  !!!_bt_first| forward: 0, first_offset: 1, so->n_prefetch_blocks: 5, stack->bts_offset: 7
PG:2024-11-21 18:09:54.280 GMT [3461271] LOG:  !!!_bt_first| skip: -2
```

So, we can see negative `i` here:
```
    /* Start prefetching for index only scan */
    if (so->prefetch_maximum > 0 && stack != NULL && scan->xs_want_itup) /* index only scan */
    {
        int first_offset = _bt_read_parent_for_prefetch(scan, stack->bts_blkno, dir);
        int skip = ScanDirectionIsForward(dir)
            ? stack->bts_offset - first_offset
            : first_offset + so->n_prefetch_blocks - 1 - stack->bts_offset;
        Assert(so->n_prefetch_blocks >= skip);
        so->current_prefetch_distance = INCREASE_PREFETCH_DISTANCE_STEP;
        so->n_prefetch_requests = Min(so->current_prefetch_distance, so->n_prefetch_blocks - skip);
        so->last_prefetch_index = skip + so->n_prefetch_requests;
        for (int i = skip; i < so->last_prefetch_index; i++)
            PrefetchBuffer(rel, MAIN_FORKNUM, so->prefetch_blocks[i]);
    }
```

But the BlockNumberIsValid() assert fails only when so->prefetch_blocks[i] contains -1, so it happens not every time when i is negative.

While testing, I also saw another assertion failure:
```
PG:TRAP: FailedAssertion("so->n_prefetch_blocks >= skip", File: ".../neon/vendor/postgres-v14/src/backend/access/nbtree/nbtsearch.c", Line: 1479, PID: 814781)
```

I could not find a good clean way to reproduce this yet, except for running multiple test instances in a loop for an hour/two, though with the following "forced ios" modification (which makes test_pg_regress fail due to unexpected outputs, but it doesn't matter here):
```
--- a/src/backend/access/index/genam.c
+++ b/src/backend/access/index/genam.c
@@ -107 +107 @@ RelationGetIndexScan(Relation indexRelation, int nkeys, int norderbys)
-    scan->xs_want_itup = false; /* may be set later */
+    scan->xs_want_itup = true;
```
and `sed 's/polygon //' -i src/test/regress/parallel_schedule` # needed to avoid an unrelated failure

running multiple test instances simultaneously and looking for FailedAssertion in test_output/, I can quickly get failures as below:
```
7       ======================== 1 failed in 395.79s (0:06:35) =========================
4       ======================== 1 failed in 399.26s (0:06:39) =========================
6       ======================== 1 failed in 436.25s (0:07:16) =========================
9       ======================== 1 failed in 820.90s (0:13:40) =========================
3       ======================== 1 failed in 822.12s (0:13:42) =========================
8       ======================== 1 failed in 823.63s (0:13:43) =========================
5       ======================== 1 failed in 825.26s (0:13:45) =========================
2       ======================== 1 failed in 826.89s (0:13:46) =========================
1       ======================== 1 failed in 828.05s (0:13:48) =========================
10      ======================== 1 failed in 836.52s (0:13:56) =========================
```

```
test_output/test_pg_regress_7[debug-pg14-None]/repo/endpoints/ep-1/compute.log
PG:TRAP: FailedAssertion("so->n_prefetch_blocks >= skip", File: ".../neon//vendor/postgres-v14/src/backend/access/nbtree/nbtsearch.c", Line: 1479, PID: 2270161)
...
PG:2024-11-24 16:42:25.638 GMT [2262658] DETAIL:  Failed process was running: INSERT INTO itest1 DEFAULT VALUES;

test_output/test_pg_regress_4[debug-pg14-None]/repo/endpoints/ep-1/compute.log
PG:TRAP: FailedAssertion("so->n_prefetch_blocks >= skip", File: ".../neon//vendor/postgres-v14/src/backend/access/nbtree/nbtsearch.c", Line: 1479, PID: 2270863)
...
PG:2024-11-24 16:42:31.958 GMT [2262430] DETAIL:  Failed process was running: CREATE INDEX test_replica_identity_hash ON test_replica_identity USING hash (nonkey);

test_output/test_pg_regress_6[debug-pg14-None]/repo/endpoints/ep-1/compute.log
PG:TRAP: FailedAssertion("so->n_prefetch_blocks >= skip", File: ".../neon//vendor/postgres-v14/src/backend/access/nbtree/nbtsearch.c", Line: 1479, PID: 2269994)
...
PG:2024-11-24 16:43:12.463 GMT [2262483] DETAIL:  Failed process was running: DROP POLICY p2 ON t1;
```

**Comment by bayandin** [comment]
Good find @alexanderlaw!
That should be fixed by https://github.com/neondatabase/neon/pull/9867

**Comment by alexanderlaw** [comment]
@bayandin , unfortunately, with the patch https://github.com/neondatabase/postgres/compare/284ae56be2397fd3eaf20777fa220b2d0ad968f5...7af94013de364fbe0c47a389cb4c0575d4992c60 applied, I'm still getting:
```
PG:TRAP: FailedAssertion("so->n_prefetch_blocks >= skip", File: "...//vendor/postgres-v14/src/backend/access/nbtree/nbtsearch.c", 
...
PG:2024-11-25 03:52:13.123 GMT [3654398] DETAIL:  Failed process was running: update people set fn.first = 'Jack';
````
using the same "forced ios" testing method.

**Comment by alexanderlaw** [comment]
With an auxiliary Assert added to the latest patch:
```
+        if (so->n_prefetch_blocks >= skip)
+        {
+            so->current_prefetch_distance = INCREASE_PREFETCH_DISTANCE_STEP;
+            so->n_prefetch_requests = Min(so->current_prefetch_distance, so->n_prefetch_blocks - skip);
+            so->last_prefetch_index = skip + so->n_prefetch_requests;
+            for (int i = skip; i < so->last_prefetch_index; i++)
+{
+Assert(i >= 0);
+                PrefetchBuffer(rel, MAIN_FORKNUM, so->prefetch_blocks[i]);
+}
+        }
```

I can see it triggered like this:
```
8       ======================== 1 failed in 378.53s (0:06:18) =========================
7       ======================== 1 passed in 977.77s (0:16:17) =========================
9       ======================== 1 passed in 981.50s (0:16:21) =========================
5       ======================== 1 passed in 983.19s (0:16:23) =========================
4       ======================== 1 passed in 984.47s (0:16:24) =========================
10      ======================== 1 passed in 993.43s (0:16:33) =========================
6       ======================== 1 passed in 997.41s (0:16:37) =========================
3       ======================== 1 passed in 998.07s (0:16:38) =========================
2       ======================== 1 passed in 999.05s (0:16:39) =========================
1       ======================== 1 passed in 1000.31s (0:16:40) ========================

test_output/test_pg_regress_8[debug-pg14-None]/repo/endpoints/ep-1/compute.log
PG:TRAP: FailedAssertion("i >= 0", File: ".../vendor/postgres-v14/src/backend/access/nbtree/nbtsearch.c", Line: 1489, 
...
PG:2024-11-25 07:56:52.578 GMT [3917163] DETAIL:  Failed process was running: SELECT table_name, column_name, column_default, is_nullable, is_identity, identity_generation, identity_start, identity_increment, identity_maximum, identity_minimum, identity_cycle FROM information_schema.columns WHERE table_name LIKE 'itest_' ORDER BY 1, 2;
```

(I've disabled the troublesome polygon's query more granularly for 'make check' to pass cleanly with the "forced ios" mod: [fix-polygon.sql-for-forced-ios.patch.txt](https://github.com/user-attachments/files/17899698/fix-polygon.sql-for-forced-ios.patch.txt).)
