### ISSUE TITLE
One reason for test_many_timelines to be flaky

### ISSUE THREAD

**Issue by alexanderlaw** [neondatabase/neon#9920]
When running multiple (15) test_wal_acceptor.py::test_many_timelines instances in a loop, I observed the same failure as in:

https://neon-github-public-dev.s3.amazonaws.com/reports/pr-9067/11021461928/index.html#testresult/42b94c68c928d889
[release-pg14]
Duration: 2s 111ms 
```
AssertionError: expected single sample for safekeeper_flush_lsn {'tenant_id': 'ed9c1054bbe0288b43c23fc0012c971a', 'timeline_id': '69828d5b92469f7513ad7ea0d3257c10'},
found []
```

https://neon-github-public-dev.s3.amazonaws.com/reports/pr-8310/10595562170/index.html#suites/82004ab4e3720b47bf78f312dabe7c55/9a9a9ff5ae5d2b9/retries
[release-pg16]
Duration: 7s 729ms 
```
AssertionError: expected single sample for safekeeper_flush_lsn {'tenant_id': '290097b9271485be76ebb2c88223f9aa', 'timeline_id': 'd1dce5abfe6d20e1d5dc0afe6f0609ad'},
found []
```

In my environment, the testing loop fails on iterations 14, 30, 39, 61:
```
ITERATION 61
...
11      =================== 1 failed, 1 warning in 64.16s (0:01:04) ====================
...
11  2024-11-28 04:20:17.802 INFO [test_wal_acceptor_11.py:209] after CREATE TABLE: [TimelineMetrics(timeline_id=TimelineId("f79dac7e52112567e569305ef66b9abf"), last_record_lsn=Lsn("0/1527468"), flush_lsns=[Lsn("0/1527468"), Lsn("0/1527468"), Lsn("0/1527468")], commit_lsns=[Lsn("0/1527468"), Lsn("0/1527468"), Lsn("0/1527468")]), TimelineMetrics(timeline_id=TimelineId("b285406dc846026cb8211e4be1ff59c0"), last_record_lsn=Lsn("0/1527468"), flush_lsns=[Lsn("0/1527468"), Lsn("0/1527468"), Lsn("0/1527468")], commit_lsns=[Lsn("0/1527468"), Lsn("0/1527468"), Lsn("0/1527468")]), TimelineMetrics(timeline_id=TimelineId("7e11fed3c12d16c3333f16ff2377b57e"), last_record_lsn=Lsn("0/1516B18"), flush_lsns=[Lsn("0/152D5A8"), Lsn("0/152D5A8"), Lsn("0/14FC3C0")], commit_lsns=[Lsn("0/152D5A8"), Lsn("0/152D5A8"), Lsn("0/14FC3C0")])]
11  2024-11-28 04:20:17.809 INFO [neon_fixtures.py:295] Executing query: INSERT INTO t SELECT generate_series(1,100000), 'payload'
11  2024-11-28 04:20:18.171 ERROR [test_wal_acceptor_11.py:235] MetricsChecker's thread failed, the test will be failed on .stop() call
11  Traceback (most recent call last):
11    File ".../test_runner/regress/test_wal_acceptor_11.py", line 232, in run
11      collect_metrics("during INSERT INTO")
11    File ".../test_runner/regress/test_wal_acceptor_11.py", line 189, in collect_metrics
11      m.flush_lsns.append(Lsn(int(sk_m.flush_lsn_inexact(tenant_id, timeline_id))))
11                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
11    File ".../test_runner/fixtures/safekeeper/http.py", line 49, in flush_lsn_inexact
11      return self.query_one(
11             ^^^^^^^^^^^^^^^
11    File ".../test_runner/fixtures/metrics.py", line 33, in query_one
11      assert len(res) == 1, f"expected single sample for {name} {filter}, found {res}"
11             ^^^^^^^^^^^^^
11  AssertionError: expected single sample for safekeeper_flush_lsn {'tenant_id': 'a5e86a95fa884674ba87156eb76578ec', 'timeline_id': '7e11fed3c12d16c3333f16ff2377b57e'}, found []
11  2024-11-28 04:20:38.734 INFO [neon_fixtures.py:295] Executing query: INSERT INTO t SELECT generate_series(1,100000), 'payload'
11  FAILED                                                                   [100%]
11  ------------------------------ live log teardown -------------------------------
11  2024-11-28 04:20:43.402 INFO [neon_fixtures.py:849] Cleaning up all storage and compute nodes
```

Log files of that run contain (my comments added):
```
test_output/test_many_timelines_11[release-pg16]/repo/safekeepers/sk3/safekeeper-3.log
...
2024-11-28T04:19:44.817904Z  INFO starting safekeeper tenant scoped WAL service on 127.0.0.1:26018
...
2024-11-28T04:20:06.068835Z  INFO {cid=10 ttid=a5e86a95fa884674ba87156eb76578ec/7e11fed3c12d16c3333f16ff2377b57e application_name=None}: got query "START_WAL_PUSH"
    ### walproposer connecting
2024-11-28T04:20:06.271747Z  INFO {cid=10 ttid=a5e86a95fa884674ba87156eb76578ec/7e11fed3c12d16c3333f16ff2377b57e application_name=None}:WAL receiver: start handshake with walproposer 127.0.0.1:47296 sysid 7442180114130944812 timeline 1
2024-11-28T04:20:14.825091Z  INFO broker: no broker updates for some time, last update: 2024-11-28T04:20:01.800Z
2024-11-28T04:20:17.768809Z  INFO WAL acceptor{cid=9 ttid=a5e86a95fa884674ba87156eb76578ec/7e11fed3c12d16c3333f16ff2377b57e}: initialized segno 1 at lsn 0/14FC3C0
2024-11-28T04:20:17.772344Z  INFO WAL acceptor{cid=9 ttid=a5e86a95fa884674ba87156eb76578ec/7e11fed3c12d16c3333f16ff2377b57e}: setting timeline_start_lsn to 0/14FC3C0 
2024-11-28T04:20:17.772368Z  INFO WAL acceptor{cid=9 ttid=a5e86a95fa884674ba87156eb76578ec/7e11fed3c12d16c3333f16ff2377b57e}: setting local_start_lsn to 0/14FC3C0
2024-11-28T04:20:17.798459Z  INFO WAL acceptor{cid=9 ttid=a5e86a95fa884674ba87156eb76578ec/7e11fed3c12d16c3333f16ff2377b57e}: start receiving WAL since 0/14FC3C0
2024-11-28T04:20:17.798556Z  INFO broker push is too long, pushed 3 timeline updates to broker in 23.192854296s
2024-11-28T04:20:17.798999Z  INFO WAL acceptor{cid=9 ttid=a5e86a95fa884674ba87156eb76578ec/7e11fed3c12d16c3333f16ff2377b57e}: restart decoder from 0/0 to 0/14FC3C0
    ### timeline initialized
2024-11-28T04:20:17.799212Z  INFO request{method=GET path=/metrics request_id=b8d4d88e-aaff-400c-b43e-1e627bca2385}:blocking: responded /metrics bytes=27960 total_ms=1583 spawning_ms=0 collection_ms=1582 encoding_ms=0
    ### metrics requested by the test
2024-11-28T04:20:17.895851Z  INFO WAL acceptor{cid=10 ttid=a5e86a95fa884674ba87156eb76578ec/7e11fed3c12d16c3333f16ff2377b57e}: processed greeting from walproposer 5219666FF632A14040F9EC30F0AEC5A3, sending term 2
2024-11-28T04:20:17.895909Z  INFO {cid=10 ttid=a5e86a95fa884674ba87156eb76578ec/7e11fed3c12d16c3333f16ff2377b57e application_name=None}:WAL receiver:{term=2 last_log_term=2 flush_lsn=0/151AF10 commit_lsn=0/14FC3C0}: terminated: received Terminate
    ### walproposer sent Terminate due to timeout
2024-11-28T04:20:17.895907Z  INFO manager{ttid=a5e86a95fa884674ba87156eb76578ec/7e11fed3c12d16c3333f16ff2377b57e}: timeline active=false now, remote_consistent_lsn=0/14FC3C0, commit_lsn=0/14FC3C0
    ### timeline 7e11fed3c12d16c3333f16ff2377b57e becomes inactive
2024-11-28T04:20:17.895916Z  INFO {cid=9 ttid=a5e86a95fa884674ba87156eb76578ec/7e11fed3c12d16c3333f16ff2377b57e application_name=None}:WAL receiver:{term=2 last_log_term=2 flush_lsn=0/151AF10 commit_lsn=0/14FC3C0}: terminated: received Terminate
2024-11-28T04:20:17.895966Z  INFO {cid=10 ttid=a5e86a95fa884674ba87156eb76578ec/7e11fed3c12d16c3333f16ff2377b57e application_name=None}: Disconnected (Broken pipe (os error 32))
2024-11-28T04:20:17.895970Z  INFO {cid=9 ttid=a5e86a95fa884674ba87156eb76578ec/7e11fed3c12d16c3333f16ff2377b57e application_name=None}: Disconnected (Broken pipe (os error 32))
2024-11-28T04:20:18.064517Z  INFO {cid=11 ttid=a5e86a95fa884674ba87156eb76578ec/7e11fed3c12d16c3333f16ff2377b57e application_name=None}: got query "START_WAL_PUSH"
    ### walproposer reconnecting
---

---
test_output/test_many_timelines_11[release-pg16]/repo/endpoints/ep-3/compute.log
PG:2024-11-28 04:20:06.068 GMT [3178127] LOG:  [WP] connecting with node 127.0.0.1:26009 
PG:2024-11-28 04:20:06.068 GMT [3178127] LOG:  [WP] connecting with node 127.0.0.1:26018
PG:2024-11-28 04:20:06.068 GMT [3178127] LOG:  [WP] connected with node 127.0.0.1:26009
PG:2024-11-28 04:20:06.068 GMT [3178127] LOG:  [WP] connected with node 127.0.0.1:26018
PG:2024-11-28 04:20:16.049 GMT [3178127] LOG:  [WP] received AcceptorGreeting from safekeeper 127.0.0.1:26009, term=2
PG:2024-11-28 04:20:16.049 GMT [3178127] LOG:  [WP] requesting vote from 127.0.0.1:26009 for term 2
PG:2024-11-28 04:20:16.049 GMT [3178127] LOG:  [WP] got VoteResponse from acceptor 127.0.0.1:26009, voteGiven=0, epoch=2, flushLsn=0/151AF10, truncateLsn=0/14FC3C0, timelineStartLsn=0/14FC3C0
PG:2024-11-28 04:20:16.049 GMT [3178127] LOG:  [WP] sending elected msg to node 1 term=2, startStreamingAt=0/151AF10 (lastCommonTerm=2), termHistory.n_entries=1 to 127.0.0.1:26009, timelineStartLsn=0/14FC3C0
PG:2024-11-28 04:20:16.052 GMT [3178127] LOG:  standby "walproposer" is now a synchronous standby with priority 1
PG:2024-11-28 04:20:17.064 GMT [3178127] WARNING:  [WP] terminating connection to safekeeper '127.0.0.1:26018' in 'handshake (receiving)' state: no messages received during the last 10000ms or connection attempt took longer than that
    ### compute disconnects from sk3 due to safekeeper_connection_timeout (10 seconds by default) exceeded
PG:2024-11-28 04:20:18.064 GMT [3178127] LOG:  [WP] connecting with node 127.0.0.1:26018
PG:2024-11-28 04:20:18.064 GMT [3178127] LOG:  [WP] connected with node 127.0.0.1:26018
```

With additional logging added, I could get more detailed information to explain the failure:
1) walproposer sends Terminate on timeout to safekeeper/WalReceiver, which reacts on this by unregistering walreceiver (via walreceiver_guard) and that, in turn, decreases num_computes for a timeline, to 0.
2) the timeline becomes inactive in timeline_manager::main_task(), via mgr.update_is_active().
3) if collect_timeline_metrics() called while walproposer is not reconnected yet, it skips the inactive timeline, so a resulting metric set doesn't contain the safekeeper_flush_lsn metric for the timeline, which is the test would like to see.

Thus, with the following patch applied:
```py
--- a/test_runner/regress/test_wal_acceptor.py
+++ b/test_runner/regress/test_wal_acceptor.py
@@ -154,7 +154,9 @@ def test_many_timelines(neon_env_builder: NeonEnvBuilder):
     endpoints = []
     for branch_name in branch_names:
         new_timeline_id = env.create_branch(branch_name)
-        endpoints.append(env.endpoints.create_start(branch_name))
+        endpoints.append(env.endpoints.create_start(branch_name,
+           config_lines=["neon.safekeeper_connect_timeout='300s'"]
+        ))
```
300 iterations passed without such a failure for me.

Still, the referenced Allure reports show different test duration (less than 10 seconds), so I think those failures can't be caused by safekeeper timeout and disconnection of walproposer (walreceiver unregistering). On the other hand, they might be caused by the opposite — walreceiver not being registered at the moment when metrics being collected. I can't produce such failures on my workstation, but the following modification:
```rust
--- a/safekeeper/src/receive_wal.rs
+++ b/safekeeper/src/receive_wal.rs
@@ -75,2 +75,3 @@ pub fn new() -> Arc<WalReceivers> {
     pub fn register(self: &Arc<WalReceivers>, conn_id: Option<ConnectionId>) -> WalReceiverGuard {
+if rand::random() {std::thread::sleep(core::time::Duration::from_millis(1000));}
```
confirms this theory — the loop
```bash
for i in `seq 10`; do echo "ITERATION $i"; DEFAULT_PG_VERSION=16 BUILD_TYPE=release poetry run pytest test_runner/regress/test_wal_acceptor.py::test_many_timelines >/tmp/test.log 2>&1;
grep -E '1 (pass|fail)' /tmp/test.log;
grep 'expected single sample for' /tmp/test.log && break;
done

```

fails for me on iterations 2, 3, 1 as below:
```
ITERATION 1
============================== 1 failed in 6.03s ===============================
>       assert len(res) == 1, f"expected single sample for {name} {filter}, found {res}"
E       AssertionError: expected single sample for safekeeper_flush_lsn {'tenant_id': '4f02fbb0a0df7cbf48b3433f2cde0536', 'timeline_id': '08d02dbe40a51862d79fc8ebf30594c9'}, found []
```

**Comment by areyou1or0** [comment]
Sensitive data detected in your issue at line 79. Please remove it immediately. Matched content: ep-3
